language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']


before_script:
  - mkdir build
  - cd build
  - cmake .. -DCC_COMMS_LIB_ONLY=ON

script:
  - make VERBOSE=1
  - ctest

