language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages: 
            - g++-5
            - cmake
            - cmake-data

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCC_COMMS_LIB_ONLY=ON

script:
  - make VERBOSE=1
  - ctest

