language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - ppa:george-edison55/cmake-3.x
          packages: 
            - g++-5
            - cmake
      env: CC=gcc-5 CXX=g++-5

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCC_COMMS_LIB_ONLY=ON

script:
  - make VERBOSE=1
  - ctest

