language: cpp
sudo: true
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages: 
            - g++-5
            - cmake
            - cmake-data
      env: _CC=gcc-5 _CXX=g++-5
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - beineri/opt-qt551            
          packages: 
            - g++-5
            - cmake
            - cmake-data
            - qt-latest
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=Release
      
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551 -y
  - sudo apt-get update -q
  - sudo apt-get install qt55declarative -y      

before_script:
  - mkdir build
  - cd build
  - CC=${_CC} CXX=${_CXX} cmake .. ${_BUILD}

script:
  - VERBOSE=1 make install
  - ctest

