language: cpp
sudo: true
notifications:
  email: false

matrix:
  include:
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=Release
    - os: linux
      env: _CC=gcc-5 _CXX=g++-5 _BUILD=-DCMAKE_BUILD_TYPE=MinSizeRel      
      
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.9 main" -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 cmake cmake-data qt55declarative qt55serialport -y      

before_script:
  - mkdir build
  - cd build
  - source /opt/qt55/bin/qt55-env.sh
  - CC=${_CC} CXX=${_CXX} cmake .. ${_BUILD}

script:
  - VERBOSE=1 make install
  - ctest

